// Pages that define their own `openGraph` replace the inherited object, which drops the site-wide share
// image generated by app/opengraph-image.js. Spread this into those pages' openGraph metadata.
export const defaultShareImage = {
  url: '/opengraph-image',
  width: 1200,
  height: 630,
  alt: 'AIDocumentAgent: AI agents that check the details in your documents',
};
